### ISSUE TITLE
need to compile your own version of ONNXRuntime

### ISSUE THREAD

**Issue by flutter-painter** [nmfisher/flutter_sherpa_onnx#1]
Hi Nick,

Thank you for inviting me here and providing precious guidelines.
I am stuck at compiling ONNXRuntime
I gathered that it must be fetched here : https://github.com/microsoft/onnxruntime
And the built using the script.
But it failed both for ios and android for me. I don't doubt that persistence and issue opening will solve this.
Yet I fail to understand why we needs to compile our own versions.

Wouldn't it be possible to use the same runtimes as yours ?
If they are too heavy for git, how about hugging face or a good old gdrive ?

**Comment by dkjazz** [comment]
I pulled all the required repos and followed @flutter-painter changes as welll and getting an error when trying to run the example (when tapping CreateRecognizer)

```
[ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'CreateOnlineRecognizer': dlsym(RTLD_DEFAULT, CreateOnlineRecognizer): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      NativeLibrary._CreateOnlineRecognizerPtr (package:flutter_sherpa_onnx/generated_bindings.dart:34:67)
#2      NativeLibrary._CreateOnlineRecognizerPtr (package:flutter_sherpa_onnx/generated_bindings.dart)
#3      NativeLibrary._CreateOnlineRecognizer (package:flutter_sherpa_onnx/generated_bindings.dart:36:40)
#4      NativeLibrary._CreateOnlineRecognizer (package:flutter_sherpa_onnx/generated_bindings.dart)
#5      NativeLibrary.CreateOnlineRecognizer (package:flutter_sherpa_onnx/generated_bindings.dart:26:12)
#6      FlutterSherpaOnnxFFIIsolateRunner._onCreateRecognizerCommandReceived (package:flutter_sherpa_onnx/flutter_sherpa_onnx_ffi_isolate.dart:154:24)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
I'm using Version 15.2. Do you have any suggestions on how to solve it?

**Comment by nmfisher** [comment]
@dkjazz you probably need to turn off dead code stripping and/or change "Strip Style" to "Non-global symbols".

Does the example project work?

**Comment by Ityulei** [comment]
Hello, my side is currently not working.
![201715762136_ pic_hd](https://github.com/nmfisher/sherpa_onnx_dart/assets/130621344/8c438126-e015-4e01-8fc2-43e1ae030979)
